### ISSUE TITLE
Similarity search: Empty _gene_ontology_terms.tsv file

### ISSUE THREAD

**Issue by AlexGaithuma** [harta55/enTAP#106]
Hi, thanks for this amazing tool. 

I ran successfully the pipeline but the Similarity search, processed files
 
    * _gene_ontology_terms.tsv

are all empty. What am I doing wrong? I would like to have the gene_ontology_terms from the diamond databases rather than the eggnog database.

**Comment by harta55** [comment]
During the similarity search stage, this file will only be populated if you are aligning against a UniProt (like swiss-prot or trembl) database where EnTAP is able to pull the relevant GO terms.

Just as a side note as well, future updates of EnTAP will be on GitLab instead of GitHub (https://gitlab.com/PlantGenomicsLab/EnTAP)!

**Comment by AlexGaithuma** [comment]
Thanks.
I am using UniProt trembl as my database. and 1st line of blastx_nucleotide_trinity_final_uniprot_trembl.out is:

       TRINITY_DN271_c0_g1_i2	tr|A0A654EA48|A0A654EA48_ARATH	100	482	0	0	1574	129	1	482	0.0  930	84.1	tr|A0A654EA48|A0A654EA48_ARATH Protein DETOXIFICATION OS=Arabidopsis thaliana OX=3702  GN=AN1_LOCUS1648 PE=3 SV=1

**Comment by harta55** [comment]
Ah apologies, Swiss-Prot is only supported right now! So you'd need to configure that, instead of trembl , if you wanted to pull GO terms for that stage. We may consider supporting the unreviewed/trembl database in the future
