### ISSUE TITLE
Error in reading Serialized EnTAP database

### ISSUE THREAD

**Issue by chani118** [harta55/EnTAP#13]
I am trying to install EnTAP on my server and have run into problems when trying to verify the main execution stage with the test data. I have confirmed our server has all the necessary dependencies installed, and received no errors through the configuration stages. I also did not get an error when I ran the configuration step on the test database. However, when I try and run the entire pipeline on the test data using the command:
EnTAP --runP -i test_data/trinity.fnn -d test_data/bin/swiss_prot_test.dmnd
Error code: 72
Error code not recognized.
Unable to initialize EnTAP database

EnTAP Database Error: Unable to read Serialized EnTAP database: Failed to read 1565 bytes from input stream! Read 1402

**Comment by harta55** [comment]
Hello,
I will look into this shortly. In the meantime, here's two quick workarounds you can try (both require internet connection):

1) I would try deleting the EnTAP binary database that has been created and running a quick configuration again with the "--data-generate" flag (the other portions of configuration will be skipped as long as the paths are correct in your config file). This will generate it locally rather than downloading from the FTP. 

2) You can also run configuration again with "--data-type 1" flag. This will download the SQL version of the database which may have better compatibility with your system. When you use "runP" or "runN" you will need to specif the "data-type 1" flag again instructing EnTAP to look for and use the SQL version.

Information on this is in the docs as well.

**Comment by harta55** [comment]
Issue has not come up again. Recent structures of the serialized database may have resolved this issue.

**Comment by Artifice120** [comment]
I have the same issue.

![Uploading image.png…]()

**Comment by Artifice120** [comment]
Figured it out, just needed to update the paths in the config files using the paths given in the --config  debug text file
