### ISSUE TITLE
error::too_many_columns

### ISSUE THREAD

**Issue by Asoorni** [harta55/EnTAP#7]
I am using EnTAP version: 0.8.4. But I face with an error:

terminate called after throwing an instance of 'io::error::too_many_columns'
  what():  Too many columns in line 1 in file "outfiles/ontology/EggNOG/annotation_results.emapper.annotations_alt".

Would you help me to resolve this issue?

Aboozar,

**Comment by johnne** [comment]
Hi @Asoorni ,
Are you using the eggnog-mapper version contained within the EnTAP repository or an external version? I ran into exactly this problem as well when running the test dataset with eggnog-mapper from an external installation (latest bioconda version). I think it has to do with the fact that emapper.py now reports Bigg reaction hits in the annotation output so that there are 13 columns instead of 12 (which the EnTAP csv parser seems to expect).

I tried running the emapper.py version contained in the EnTAP repository but ended up with a different error at the emapper.py step. Below is the error from `outfiles/ontology/EggNOG/annotation_std.err`:

> Traceback (most recent call last):
  File "EnTAP-0.8.4-beta/libs/eggnog-mapper/emapper.py", line 1082, in <module>
    main(args)
  File "EnTAP-0.8.4-beta/libs/eggnog-mapper/emapper.py", line 260, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "EnTAP-0.8.4-beta/libs/eggnog-mapper/emapper.py", line 675, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
sqlite3.OperationalError: no such table: member

This is using the latest eggnog database so there seems to be some incompatibility with the old emapper.py version contained in EnTAP and the new eggnog database, as well as between the EnTAP parser and the latest emapper.py version.

**Comment by harta55** [comment]
Hello,

Apologies for the delay. @johnne is exactly right. You must use the version contained within the EnTAP repo, some newer versions of eggnog-mapper have switched to a different SQL database release that include Bigg lookups. This is currently unsupported by EnTAP. 

@johnne I suspect your issue is due to the EggNOG database being used, as you mentioned. If you replace your eggnog.db file with the following, you should have no issues:
http://eggnogdb.embl.de/download/emapperdb-4.5.0/eggnog.db.gz

Compatibility between the two is something I have already been looking into and a new EnTAP release should be finished within the next week or so that will resolve any incompatibility issues. I am adding this to the FAQ for current versions of EnTAP.

**Comment by johnne** [comment]
@harta55 Thanks for the reply!

**Comment by Asoorni** [comment]
Thanks @harta55 and @johnne. 

EnTAP works well with internal eggnog-mapper version and EggNOG database (v 4.5).
